version: '3.8'

services:
  velaaroma-web:
    build: .
    container_name: velaaroma_local
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - velaaroma-network

networks:
  velaaroma-network:
    driver: bridge